# $FreeBSD$

env:
  CIRRUS_CLONE_DEPTH: 1

task:
  freebsd_instance:
    matrix:
      image: freebsd-12-1-release-amd64
      image_family: freebsd-13-0-snap
    cpu: 8
    memory: 24G
  timeout_in: 120m
  install_script:
  - pkg install -y bash cmake git-lite ninja py37-psutil
  script:
  - mkdir -p build
  - cd build
  - cmake -GNinja -DCMAKE_BUILD_TYPE=Release
    -DLLVM_ENABLE_PROJECTS="clang;lldb" ../llvm
  - ninja
  lld_test_script:
  - cd build
  - ninja check-lld
  clang_test_script:
  - cd build
  - ninja check-clang
  lldb_test_script:
  - cd build
  - env FREEBSD_REMOTE_PLUGIN=1 ninja check-lldb
